# Generated by Django 4.0.3 on 2022-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_todomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
