# Generated by Django 4.0.3 on 2022-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todomodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='listorder',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
